# Generated by Django 2.2.4 on 2019-08-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default='https://github.com/rae0924'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='on_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='page_url_name',
            field=models.CharField(default='raedl-home', max_length=100),
        ),
    ]
