# Generated by Django 2.2.5 on 2019-10-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='article_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
