# Generated by Django 2.2.5 on 2019-10-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorial_article_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='path_name',
        ),
    ]
